### ISSUE TITLE
Faild to download the modules

### ISSUE THREAD

**Issue by sacredic** [Androidacy/MagiskModuleManager#101]
**Describe the bug**
When i click yhe istall modules option，the screen show that failed to download the modules zip with an error report 'potential SSL interception detected"

**To Reproduce**

**Expected behavior**
I expect that fix the error ---- can download and install the modules

**Screenshots**
![Screenshot_20240313-003327](https://github.com/Androidacy/MagiskModuleManager/assets/35089496/a375e746-77cf-46cd-836f-ad996aab2489)

**Device info(please complete the following information):**
 - Device: google pixel 7pro
 - OS: android 14，AP1A.240305.019.A1
 - App Version AMM 2.3.6

**Comment by Wollert60** [comment]
Wont work dude

**Comment by a0193143** [comment]
This only happens with Magisk Alt Repo, and AMM dev seems not interest with solving this issue.
Fine, I'll switch to MRepo.
