### ISSUE TITLE
F-Droid flavor

### ISSUE THREAD

**Issue by gilbsgilbs** [Androidacy/MagiskModuleManager#25]
With the recent change in the ownership of this project, I'd like to know if you're still willing to maintain the F-Droid ("fdroid") flavor of this app and if we can update the F-Droid metadata to point towards this project rather than the archived one (which seems broken at the moment).

Note that this has some implications in term of maintenance: https://f-droid.org/en/docs/Inclusion_Policy/ . But the TLDR is:

- No dependency to proprietary librairies (such as Google Services). If you're willing to include such dependency, you have to provide an alternative implementation for the F-Droid flavor that doesn't require it.
- Sane defaults regarding privacy (e.g. telemetry and automatic crash reports should be opt-in)
- Report any feature that may compromise privacy (such as relying on a non-free server back-end), be a nuisance to users (such as using ads) or restrain their rights (such as using non-free artwork). More info [here](https://f-droid.org/en/docs/Anti-Features/).

If that's OK for you, I'd like to know if you're planning on making some kind of rebranding at some point (such as changing the appid or application name) because that would affect the F-Droid metadata.

**Comment by gilbsgilbs** [comment]
Great. Thanks for your prompt reply 🙂 .

**Comment by gilbsgilbs** [comment]
I missed that the metadata was already up-to-date, sorry for the noise then.

However, the current version published on F-Droid doesn't seem to work on my device and shows the app logo forever. Can you reproduce?

**Comment by gilbsgilbs** [comment]
Oh, right. It seems that this version isn't built yet. Thank you again 🙏.

**Comment by LeeBinder** [comment]
No update yet on https://f-droid.org/en/packages/com.fox2code.mmm.fdroid/ Do they know for sure that 2.1.1 has been published?
