### ISSUE TITLE
[Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [Androidacy/MagiskModuleManager#58]
**Is your feature request related to a problem? Please describe.**

The launcher icon on Android 13 & up isn't themed

**Describe the solution you'd like**

Implement themed launcher icon support

**Describe alternatives you've considered**

None

**Additional context**
[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#User_Theming](url)

**Comment by Vosjedev** [comment]
your link is broken, [this one](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#User_Theming) will work

**Comment by Vosjedev** [comment]
I think he means icon packs. Not sure though, can't test that.

**Comment by sebastien46** [comment]
Sorry for the inconvenience, it was a one-time error, now it works just fine. Have a nice day.
