### ISSUE TITLE
kernelsu

### ISSUE THREAD

**Issue by Hamood111** [Androidacy/MagiskModuleManager#67]
I hope nex update supposed kernelsu 
![Screenshot_2023-08-31-05-34-49-580_me weishu kernelsu](https://github.com/Androidacy/MagiskModuleManager/assets/116981650/3bba84fe-c359-43d9-8387-c34d84e54ac1)
![Screenshot_2023-08-31-05-35-09-464_com fox2code mmm](https://github.com/Androidacy/MagiskModuleManager/assets/116981650/bde80c67-c1bb-4b2f-ba8b-93004d8a54a3)

**Comment by CapitanArdeshir** [comment]
Please Fix That Problem , Nor Work With KernelSU
