### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Androidacy/MagiskModuleManager#70]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5064858593#L800

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/b4297bdb948b0d5fabbd42e5704d87b127234b31

**Comment by licaon-kter** [comment]
The sed patching was added as needed at that point in time, we'll see if they still apply.

**Comment by linsui** [comment]
I removed sentry in 2.3.0 because it doesn't build with that enable. :shrug: https://gitlab.com/fdroid/fdroiddata/-/jobs/5051237358

**Comment by linsui** [comment]
Let me have a try.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/5077658861 It failed again.

**Comment by linsui** [comment]
It works, thanks!
